### PR TITLE
make containers interactive

### LINKED ISSUE #109: make Docker interactive on fail
It would be great be be able to connect into Docker container on failed build to debug it.

### PR DESCRIPTION
**Pull request by AtomicFS**
- on build failure open ssh server in the container and let user connect into it to debug the problem
- to enable this feature user has to pass argument `--interactive`
- into the containers add few editors (nano, vim), tools and utilities people would expect
- ssh login is with password, which is randomly generated

Fixes #109 

Testing will be pain, but I think there needs to be some. So I will take a look at it.

### CODE REVIEW

**Comment by AtomicFS** [comment]
@MDr164 review ready btw

File: action/container/ssh.go [hunk 1]
```diff
@@ -0,0 +1,158 @@
...
+	defer sshServiceTunnel.Stop(ctx) // nolint:errcheck
+
+	// Get and print instructions on how to connect
+	sshAddress, err := sshServiceTunnel.Endpoint(ctx)
+	if err != nil {
+		fmt.Println("problem getting address")
+		return err
+	}
+	sshAddressSplit := strings.Split(sshAddress, ":")
+	opts.Port = sshAddressSplit[1]
```
Comment (MDr164) [inline action/container/ssh.go:130]: Why are you setting the port here out side the lock and three lines further down inside the mutex lock?

**Review by MDr164 — COMMENTED** [review]
Just some minor things about the opts generated from the created tunnel. If we can guarantee that `sshAddressSplit` is always at least 2 elements large I'm fine with the current approach. Otherwise we should sanity check it to not do some out of bounds access by accident and causing a crash.

File: action/container/ssh.go (hunk 1 above)
Comment (AtomicFS) [reply action/container/ssh.go:130]: that is some copy-paste error since I set the port twice :D

Comment (AtomicFS) [reply action/container/ssh.go:130]: I will make this into function (method of the struct) and add some security to it.

**Comment by AtomicFS** [comment]
@MDr164 what about this?

File: action/container/ssh.go [hunk 2]
```diff
@@ -0,0 +1,187 @@
...
+// Wait calls WaitFunc
+func (s OptsOpenSSH) Wait() {
+	s.WaitFunc()
+}
+
+// Address function parses provided string and populates IPv4 and Port (port defaults to 22 if not found)
+func (s *OptsOpenSSH) Address(address string) error {
+	s.MutexData.Lock()
+	var err error
+	err = nil
```
Comment (MDr164) [inline action/container/ssh.go:43]: You can drop this line, Go always initializes with the zero/nil value of the underlying datatype. So the line above is sufficient here.

**Comment by AtomicFS** [comment]
Just found issue with the wait function. It test it works find, but when using manually, it fails to exit.

```
47: start /usr/sbin/sshd -D
47: > in service 6asqg9rb2ii4g
Connect into the container with:
  ssh root@127.0.0.1 -p 34667 -o PreferredAuthentications=password
Password is:
  n4sTE5VlEZCJV3Wh
SSH up and running

^Ctask: Signal received: "interrupt"
task: Failed to run task "build-edk2": exit status 130
```

**Comment by AtomicFS** [comment]
Fixed, did not realize that writing into channel was also blocking,

**Review by MDr164 — APPROVED** [review]
